import { Inter } from "next/font/google";
import Navbard from '@/components/shared/Navbar/Nav'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio Franky Vargas",
  description: "Generated by create next app",
  icons: {
    icon: ['/favicon.ico?v=4'],
    apple: ['']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-primary  ${inter.className}`}>
        <Navbard />
        {children}
      </body>
    </html>
  );
}
