import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, unstable_setRequestLocale } from 'next-intl/server';

const inter = Inter({ subsets: ["latin"] });
import "./globals.css";

export const metadata = {
  title: "Portfolio Franky Vargas",
  description: "Generated by create next app",
  icon: ['/favicon.ico?v=4'],
};

export async function generateStaticParams() {
  const locales = ['en', 'es'];
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }) {
  const { locale } = params;
  unstable_setRequestLocale(locale);
  const messages = await getMessages(locale);

  return (
    <html lang={locale}>
      <body className={`bg-primary ${inter.className}`}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
